image: python:{{cookiecutter.lambda_python_version}}-alpine

pipelines:
  default:
    - step:
        script:
          - python setup.py ldist --include-version=False
  branches:
    master:
      - step:
          deployment: production
          script:
            - python setup.py ldist --include-version=False lupload --access-key=$ACCESS_KEY_ID_PROD --secret-access-key=$SECRET_KEY_PROD --s3-bucket=$BUCKET_NAME --s3-prefix={{cookiecutter.lupload_prefix}}
    develop:
      - step:
          deployment: test
          script:
            - python setup.py ldist --include-version=False lupload --access-key=$ACCESS_KEY_ID_DEV --secret-access-key=$SECRET_KEY_DEV --s3-bucket=$BUCKET_NAME --s3-prefix={{cookiecutter.lupload_prefix}}
