version: 2
jobs:
  build-ldist:
    docker:
      - image: circleci/python:{{cookiecutter.lambda_python_version}}
    steps:
      - checkout
      - run: python setup.py ldist
  build-lupload:
    docker:
      - image: circleci/python:{{cookiecutter.lambda_python_version}}
    steps:
      - checkout
      - run: python setup.py lupload --access-key=${ACCESS_KEY_ID} --secret-access-key=${SECRET_ACCESS_KEY} --s3-bucket=${S3_BUCKET} --s3-prefix={{cookiecutter.lupload_prefix}}
workflows:
  version: 2
  build-only:
    jobs:
      - build-ldist:
          filters:
            branches:
              only:
                - develop
  build-and-upload:
    jobs:
      - build-lupload:
          context: {{cookiecutter.circleci_lupload_context}}
          filters:
            branches:
              only:
                - master
